# Generated by Django 3.2.3 on 2021-08-29 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('function', models.CharField(choices=[(1, 'Harvest'), (2, 'Pruning'), (3, 'Scouting'), (4, 'Other')], max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
